---

- name: ohpc, Add ohpc repo
  yum_repository:
    name: OpenHPC
    file: openhpc
    description: "OpenHPC-1.3 - Base"
    baseurl: "http://build.openhpc.community/OpenHPC:/1.3/CentOS_7"
    enabled: yes
    gpgcheck: yes
    gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-OpenHPC-1"
  when: ansible_os_family == "RedHat"

- name: ohpc, Add ohpc-updates repo
  yum_repository:
    name: OpenHPC-updates
    file: openhpc
    description: "OpenHPC-1.3 - Updates"
    baseurl: "http://build.openhpc.community/OpenHPC:/1.3/updates/CentOS_7"
    enabled: yes
    gpgcheck: yes
    gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-OpenHPC-1"
  when: ansible_os_family == "RedHat"

