---

- name: infiniband_xcat, chdef network settings in compute image
  command: 'chdef -t network -o ib0 mask={{ cluster_hsn_netmask }} net={{ item }}'
  with_items: '{{ cluster_compute_nodes.xc1.ipoib }}'

- name: infiniband_xcat, chdef postboot scripts
  command: 'chdef compute -p postbootscripts=confignics'

- name: infiniband_xcat, chdef network settings in compute image
  command: 'chdef {{ item.key }} nicips.ib0={{ item.value.ipoib }} nictypes.ib0="InfiniBand" nicnetworks.ib0=ib0'
  with_dict: '{{ cluster_compute_nodes }}'
