---

#
# Mount /var/spool/slurm from the netapp
#

- name: Mount filer on /var/spool/slurm
  mount:
    src: "{{ slurm_state_source }}"
    name: /var/spool/slurm
    fstype: nfs
    opts: "rw,sync,nfsvers=3"
    state: mounted
  when: slurm_state_source is defined

#
# Ensure /var/spool/slurm/log exists
#

- name: Ensure /var/spool/slurm/log exists
  file:
    path: /var/spool/slurm/log
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Ensure /etc/slurm exists
  file:
    path: /etc/slurm
    state: directory
    owner: root
    group: root
    mode: 0755

#
# SLURM Daemon File
#
- name: slurm_config, slurm.conf
  template:
    src: slurm.conf.j2
    dest: /etc/slurm/slurm.conf
    owner: "root"
    group: "root"
    mode: "0444"
    backup: yes
  notify: restart slurmctld

- name: slurm_config, cgroup.conf
  template:
    src: cgroup.conf.j2
    dest: /etc/slurm/cgroup.conf
    owner: "root"
    group: "root"
    mode: "0444"
    backup: yes
  notify: restart slurmctld

- name: slurm_config, gres.conf
  template:
    src: gres.conf.j2
    dest: /etc/slurm/gres.conf
    owner: "root"
    group: "root"
    mode: "0444"
    backup: yes
  notify: restart slurmctld

- name: slurm_config, /etc/cron.d
  file:
    path: "/etc/cron.d"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: slurm_config, cron.d/slurm-refresh
  template:
    src: slurm-refresh.j2
    dest: /etc/cron.d/slurm-refresh
    owner: "root"
    group: "root"
    mode: "0444"
    backup: yes

#
# dynamically-loaded data files, generated by idmanager, ldap/hpcaccounts is authoritative
#

- name: slurm_config, slurm_load.dat
  copy:
    src: slurm_load.dat
    dest: /etc/slurm/slurm_load.dat
    owner: "root"
    group: "root"
    mode: "0400"
    backup: yes

- name: slurm_config, slurm_load_qos.dat
  copy:
    src: slurm_load_qos.dat
    dest: /etc/slurm/slurm_load_qos.dat
    owner: "root"
    group: "root"
    mode: "0500"
    backup: yes

#
# slurmdbd Files
#

- name: slurm_config, slurmdbd.conf
  template:
    src: slurmdbd.conf.j2
    dest: /etc/slurm/slurmdbd.conf
    owner: "root"
    group: "root"
    mode: "0400"
    backup: yes
  notify: restart slurmdbd

#
# Logrotate Files
#

- name: slurm_config, logrotate_slurm
  template:
    src: logrotate_slurm.j2
    dest: /etc/logrotate.d/slurm
    owner: "root"
    group: "root"
    mode: "0444"
    backup: yes

#
# Sysconfig Files
#

- name: slurm_config, sysconfig_slurm
  template:
    src: slurm.j2
    dest: /etc/sysconfig/slurm
    owner: "root"
    group: "root"
    mode: "0444"
    backup: yes

- name: slurm_config, sysconfig_slurmd
  template:
    src: slurmd.j2
    dest: /etc/sysconfig/slurmd
    owner: "root"
    group: "root"
    mode: "0444"
    backup: yes

- name: slurm_config, sysconfig_slurmctld
  template:
    src: slurmctld.j2
    dest: /etc/sysconfig/slurmctld
    owner: "root"
    group: "root"
    mode: "0444"
    backup: yes

#
# Prologue/epilogue config
#

- name: slurm_config, Configuration file for slurm.prolog
  template:
    src: slurm.prolog.j2
    dest: /etc/slurm/slurm.prolog
    owner: "root"
    group: "root"
    mode: "0555"
    backup: yes

- name: slurm_config, Configuration file for slurm.epilog.clean
  template:
    src: slurm.epilog.clean.j2
    dest: /etc/slurm/slurm.epilog.clean
    owner: "root"
    group: "root"
    mode: "0555"
    backup: yes

- name: slurm_configs, env files
  copy:
    src: slurm.sh
    dest: /etc/profile.d/slurm.sh
    owner: "root"
    group: "root"
    mode: "0644"

- name: slurm_configs, enable slurm
  systemd:
    name: slurmctld
    state: started
    enabled: yes

