---

- name: munge, Ensure munge is installed
  package:
    name: munge-ohpc
    state: present

- name: munge, Check to see if the munge.key exists
  local_action:
    stat path=/etc/ansible/files/fc_munge.key
  register: munge_key
  ignore_errors: True

- name: munge, munge key
  file:
    src: /etc/ansible/files/fc_munge.key
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: 0400
  when: munge_key.stat.exists

- name: munge, start munge
  systemd:
    name: munge
    state: started
    enabled: yes
