---
- name: nfs, create exports.d
  file:
    path: /etc/exports.d
    state: directory
    owner: 'root'
    group: 'root'
    mode: '0755'


- name: nfs, Create exports
  template:
    src: 'nfs_exports.j2'
    dest: '/etc/exports.d/nfs.exports'
    owner: 'root'
    group: 'root'
    mode: '0444'

- name: nfs, start NFS service
  systemd:
    name: nfs
    state: started
    enabled: yes
  when: not ansible_virtualization_type == "docker"
