---

- name: firewall, remove firewalld
  package:
    name: firewalld
    state: absent

- name: firewall, install iptables
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - iptables
    - iptables-services

- name: firewall, create iptables file
  template:
    src: iptables.j2
    dest: /etc/sysconfig/iptables
    owner: root
    group: root
    mode: 0400
  notify: 'reload iptables'

- name: firewall, ensure iptables is running
  systemd:
    name: iptables
    state: started
    enabled: yes
