---

- name: dns, create resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    mode: 0444
    backup: yes
  with_items:
    - "{{ dns_servers }}"
  when: dns_servers is defined
