---

- name: sshd, Install OpenSSH
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - openssh

- name: sshd, Create sshd_config from template
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: "root"
    group: "root"
    mode: "0440"
    backup: yes
  notify: reload sshd

- name: sshd, Make .shosts from template
  template:
    src: shosts.j2
    dest: /root/.shosts
    owner: "root"
    group: "root"
    mode: "0400"
    backup: yes

- name: sshd, Ensure /root/.ssh exists
  file:
    path: /root/.ssh
    state: directory
    mode: 0755

- name: sshd, Make authorized_keys from template
  template:
    src: authorized_keys.j2
    dest: /root/.ssh/authorized_keys
    owner: "root"
    group: "root"
    mode: "0400"
    backup: yes
  when: cm_id_rsa_key is defined

- name: sshd, Make shosts.equiv from template
  template:
    src: shosts.equiv.j2
    dest: /etc/ssh/shosts_equiv
    owner: "root"
    group: "root"
    mode: "0444"
    backup: yes

- name: sshd, Make ssh_config from template
  template:
    src: ssh_config.j2
    dest: /etc/ssh/ssh_config
    owner: "root"
    group: "root"
    mode: "0444"
    backup: yes

- name: sshd, Make ssh_known_hosts from template
  template:
    src: ssh_known_hosts.j2
    dest: /etc/ssh/ssh_known_hosts
    owner: root
    group: root
    mode: 0444
    backup: yes

- name: sshd, start sshd if not running
  systemd:
    name: sshd
    state: started
    enabled: yes
